name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile LaTeX example - basic
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/basic
        root_file: main.tex

    - name: Compile LaTeX example - sectionbib
      uses: dante-ev/latex-action@latest
      with:
        working_directory: examples/sectionbib
        root_file: main.tex
